STYLES = {
    "sos": {
        "background": {
            "image": "images/sos.png",
        },
        "font": {
            # "family": "Superstar M54",
            "family": "fonts/SuperstarM54.ttf",
            "color": "#ffffff44",
        },
        "line": {
            "width": 0.5,
            "color": "#ffffff",
        },
        "shadow": {
            "color": "#ffffff",
        },
        "animation": {
            "entering": "topslidein",
            "leaving": "bottomslideout",
            "sustaining": "vshaking",
        },
        "match": {
            "artist": "sza",
            "title_any": [
                "sos",
                "kill bill",
                "seek & destroy",
                "low",
                "love language",
                "blind",
                "used",
                "snooze",
                "notice me",
                "gone girl",
                "smoking on my ex pack",
                "ghost in the machine",
                "f2f",
                "nobody gets me",
                "conceited",
                "special",
                "too late",
                "far",
                "shirt",
                "open arms",
                "i hate u",
                "good days",
                "forgiveless",
            ],
        },
    },
    "ctrl": {
        "background": {
            "image": "images/ctrl.png",
        },
        "font": {
            # "family": "Mx437 IBM VGA 8x14",
            "family": "fonts/Mx437IBMVGA8x14.ttf",
            "color": "#51f57522",
            "size": "35px",
        },
        "line": {
            "width": 0.5,
            "color": "#1f7820",
        },
        "shadow": {
            "color": "#41cc44",
            "radius": 5,
        },
        "animation": {
            "entering": "topslidein",
            "leaving": "bottomslideout",
            "sustaining": "hshaking",
        },
        "match": {
            "artist": "sza",
            "title_any": [
                "supermodel",
                "love galore",
                "doves in the wind",
                "drew barrymore",
                "prom",
                "the weekend",
                "go gina",
                "garden (say it like dat)",
                "broken clocks",
                "anything",
                "wavy (interlude)",
                "normal girl",
                "pretty little birds",
                "20 something",
            ],
        },
    },
}
